$(document).ready(function() {
  console.log = function() {};
  console.warn = function() {};
  console.error = function() {};
  // LIBRARIES CODE
  LibVars = {};
  // PROJECT CODE
  var _that = this;
  _that.deviceID = null;
  _that.token = null;
  // Block#: 2F*VPGi3]+;Qt1MQH%MC
  function on_Button_click(e) {
    try {
      // Block#: 6tc5O+-R-4t-cM/^FpWb
      _that.deviceID = (com.fc.JavaScriptDistLib.FireBase.getUniqueDeviceId());
      // Block#: ll2GP-`,PFb-|$[,)e)@
      _that.token = (com.fc.JavaScriptDistLib.FireBase.getRefreshedToken());
      // Block#: kY5~fH-{+lKH3-.t@Dbe
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label", (String('Device ID: ') + String(_that.deviceID))); // Block#: Jc=cq,tfcu3pC8Ln9J,i
      com.fc.JavaScriptDistLib.Label.setProperty["Text"]("Label2", (String('Token: ') + String(_that.token)));
      e.stopPropagation();
    } catch(e) {
      com.fc.JavaScriptDistLib.handleExceptionNative(e);
    }
  };
  $('[obj-name="Button"]').on('click', on_Button_click);
  $('[obj-name="MainScreen"]').show().triggerHandler('show');
  history.pushState({
    'view': 'MainScreen'
  }, 'MainScreen', '?MainScreen');
});
// Generated by snapp
// 766148-281850-629843-855350
